### ISSUE TITLE
Support for DateTimeOffset

### ISSUE THREAD

**Issue by tompazourek** [MehdiK/Humanizer#379]
I think a support for DateTimeOffset would be nice complement to the existing DateTime helpers in Humanizer. DateTimeOffset works better in most cases than DateTime, since it represents a very specific moment in time and has better timezone support than the oversimplified DateTimeKind enum in DateTime type.

Please consider.

**Comment by hazzik** [comment]
:+1:

**Comment by MehdiK** [comment]
Completely agreed. This has been in my mind since V1. 

So you're volunteering to do it? ;)
