### ISSUE TITLE
Feature Request: Allow MaxUnit and MinUnit for TimeSpan

### ISSUE THREAD

**Issue by deadlydog** [MehdiK/Humanizer#388]
First off, this is a great package.  Well done :)

Right now you have the ability to specify a precision integer for TimeSpans.  This is great for hard-coded TimeSpans, but isn't flexible enough for calculated ones.  In my scenario, I want to always have the TimeSpan represented down to the second, whether the time span is for 5 minutes or 5 days.  Ideally I'm looking to be able to do something like:

    (timeSpan1 - timeSpan2).Humanize(minUnit: TimeUnit.Second)

which would generate a string like:
"5 minutes, 15 seconds"
or
"2 days, 3 hours, 2 minutes, 33 seconds"

And to go along with that, being able to specify a maxUnit would be great too, so if I had also specified maxUnit: TimeUnit.Hour, then the above string would have been:
"51 hours, 2 minutes, 33 seconds"

Right now the documentation in the ReadMe.md says that maxUnit exists, but it is not in the latest stable NuGet package, which is currently 1.33.7.  Maybe it's just still in a feature branch and not yet pushed to the NuGet Gallery?

**Comment by MehdiK** [comment]
Thanks for the nice words and suggestion @deadlydog 

Funny you should mention this as [maxUnit was implemented](https://github.com/MehdiK/Humanizer/pull/384/files) just a couple of days ago :) As you said it's not on nuget yet (will be in the next few minutes).

`minUnit` would be a nice addition too. Did you want to send us a PR? It should be relatively easy to implement on top of maxUnit.

**Comment by alimeziane** [comment]
Hi, I would like to work on this subject to participate in your project, that I find very useful. Is anyone treating this evolution or can I start it directly? 
Thanks

**Comment by MehdiK** [comment]
Thanks @blackding. Cool. Go forth and conquer!

**Comment by danielbrezoi** [comment]
Hi, I have worked on this issue and now I'll make a pull request. I have make a version that makes easy to add the implementation of years and months time units if you will want this.

**Comment by MehdiK** [comment]
Closed by #403
