### ISSUE TITLE
A collection formatter for the current culture has not been implemented yet

### ISSUE THREAD

**Issue by Bartmax** [MehdiK/Humanizer#392]
I'm pretty sure this code worked before (data may be different, but still)

var a = new DateTime[] { DateTime.UtcNow, DateTime.UtcNow.AddDays(10) };
var b = a.Humanize(); // THROWS!

A collection formatter for the current culture has not been implemented yet.

I'm not sure what I'm looking into. any help is appreciated.

**Comment by MehdiK** [comment]
Thanks for reporting the issue. It must be related to #386. On reviewing I thought that PR was backward compatible; but apparently I was wrong. What's the *current culture* you're using?

**Comment by Bartmax** [comment]
is the culture set on spanish by chrome. In cultureInfo it prints ES as the culture. hope it helps. Let me know if you need to do something on my end. I'm more than happy to help.

**Comment by ThomasMentzel** [comment]
The problem with the collection formatter is the default implementation, which throws an exception. I had the same issue in German and Danish. This is why I came up with the generalization in my pull request. 
My recommendation is using the "Regular Style" as default collection formatter, which seems the most common usage of concatenating list elements, and overwrite this for those languages which use the oxford style -or even something absolutely different.

I will create a pull request for that and the decision is up to MehdiK.

**Comment by MehdiK** [comment]
Thanks for the PR @ThomasMentzel. I like it. We left you a couple of comments on it.

I'm still wondering why it wasn't failing before and only it started failing after #386!!

**Comment by MehdiK** [comment]
This is now fixed by @ThomasMentzel and available on NuGet as v1.35.0. Thanks for reporting.

**Comment by hazzik** [comment]
Meant to be closed
