### ISSUE TITLE
There was a conflict between "mscorlib, Version=4.0.0.0" and "mscorlib, Version=2.0.5.0"

### ISSUE THREAD

**Issue by Korijn** [MehdiK/Humanizer#393]
Why are you targeting such an old version of mscorlib?

This is using the most recent versions of the nuget packages in a 4.5.1 solution.

    There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
    4>      "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.

    .....(irrelevant part removed for brevity)....

    References which depend on "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
    4>          C:\Development\Projects\.....\packages\Humanizer.1.33.7\lib\portable-win+net40+sl50+wp8+wpa81\Humanizer.dll
    4>            Project file item includes which caused reference "C:\Development\Projects\.....\packages\Humanizer.1.33.7\lib\portable-win+net40+sl50+wp8+wpa81\Humanizer.dll".
    4>              Humanizer, Version=1.33.7.0, Culture=neutral, PublicKeyToken=979442b78dfc278e, processorArchitecture=MSIL
    4>          C:\Development\Projects\.....\packages\CommonServiceLocator.1.3\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll
    4>            Project file item includes which caused reference "C:\Development\Projects\.....\packages\CommonServiceLocator.1.3\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll".
    4>              C:\Development\Projects\.....\............Infrastructure\bin\Debug\............Infrastructure.dll
    4>              C:\Development\Projects\.....\......Core\bin\Debug\......Core.dll
    4>              Unity.WebApi
    4>              Microsoft.Practices.Unity.Mvc
    4>              Microsoft.Practices.Unity.Configuration, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    4>              Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    4>              Microsoft.Practices.Unity.RegistrationByConvention
    4>              Microsoft.Practices.Unity.WebApi
    4>              Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    4>              Unity.Mvc5
    4>              C:\Development\Projects\.....\............Domain\bin\Debug\............Domain.dll

**Comment by MehdiK** [comment]
I have a feeling this is related to Unity and not Humanizer.

**Comment by MehdiK** [comment]
Actually you're right. Humanizer is "referencing" mscorlib v2.0.5.0, but indirectly. Humanizer is a PCL assembly with SilverLight support and any PCL with SL is doomed to target that version of mscorlib.
