### ISSUE TITLE
Add support for excluding certain user-defined words from pluralization / singularization

### ISSUE THREAD

**Issue by qJake** [MehdiK/Humanizer#402]
One of the places I use Humanizer is on a small recipe site. I pluralize ingredient units where possible (`cup => cups`, `slice => slices`, `lb => lbs`), but some units shouldn't be pluralized. For example, `4 ozs` looks weird, as does `6 tsps`.

Would it be possible to add an overload (or maybe a static property) to the pluralization service so that you can feed it an array of strings that you want to exclude from pluralization?

**Comment by MehdiK** [comment]
Thanks for the issue @qJake. That's a very legitimate need and something that we should support in the lib. To support this, I think we need to add an exception list to the pluralize/singularize methods that they just skip over.

Would you want to submit a PR for this?

**Comment by hazzik** [comment]
I think we just add rule, that these words are not countable.

**Comment by hazzik** [comment]
And also make `AddSingular`, `AddPlural` and `AddUncountable` public on `InflectorExtensions`

**Comment by MehdiK** [comment]
> And also make AddSingular, AddPlural and AddUncountable public on InflectorExtensions

Great idea @hazzik.

**Comment by jkodroff** [comment]
@MehdiK I took a look at this and while adding some more words to the static list would be helpful for solving the immediate problem, I think we could make this way more versatile (multiple languages, add your own rules, remove any rules you don't want for some reason, etc) if this class wasn't static and instead the list of plural/singular/irregular/uncountable was passed through a constructor.  It would also make testing easier and could lead to the dictionary being completely decoupled from the inflector.

Are you open to something more ambitious, or would it be best to just solve the problem at hand for now?  (I'm not sure I could strictly guarantee backwards compatibility but I'll certainly try.)

PS - I found this issue via http://up-for-grabs.net

**Comment by qJake** [comment]
+1 @jkodroff I really like that idea. Passing in your own vocabulary / dictionary (while providing a "sensible defaults" option or base class) would definitely solve this problem in a good way.

**Comment by jkodroff** [comment]
I'm gonna wait for the word from @MehdiK as he's the owner, but as I started to add "oz", "lb", "mL" I quickly realized I wasn't gonna get all the combos.

@qJake @MehdiK What would you think of being able to add a `humanizer-dict.json` file to the output directory and have it automatically picked up.  Content would be like:

```
{
  "plural": [
    { rule: "foo", replacement: "bar" },
    // etc
  ],
  "singular": [
    { rule: "foo", replacement: "bar" },
    // etc
  ],
  "irregular": [
    { singular: "foo", plural: "bar" },
    // etc
  ],
  "uncountable": [
    "equipment",
    // etc
  ]
}
```

Now you can update the exceptions locally and have it work immediately, and if you're felling real nice you can submit a PR to add it to the standard exceptions in the repo.

**Comment by qJake** [comment]
This project is almost pure C#... As much as I love JSON, it doesn't feel right introducing this arbitrary JSON file into a C# project.

From an "end user" point of view, I'd want to do something like this:

```csharp
var uncountableWords = new ["ml", "oz", "tbsp", "tsp", "l"];
Inflector.Initialize(new InflectorVocabulary
{
    Uncountable = uncountableWords
});
```

`InflectorDictionary` could come with the standard list of plural / singular / uncountable words that [already exist in the static constructor of `InflectorExtensions`](https://github.com/MehdiK/Humanizer/blob/2ebb647bda328bacbb9eda9bf6876d25101b7495/src/Humanizer/InflectorExtensions.cs#L56), and you could have an overload / optional parameter to denote whether or not you want to load the "default" list of start blank with your own - for example, `public InflectorVocabulary(bool inheritDefaultVocab = true) { ... }`. The property that I set (`Uncountable`) would be [unioned](https://msdn.microsoft.com/en-us/library/vstudio/bb358407%28v=vs.100%29.aspx) with some private "base" property (assuming `inheritDefaultVocab` was `true`), like `private List<string> UncountableBaseList { get; set; }` so that you have a distinct list of base and user-defined vocabularies.

This is just a quick example, obviously details need to be worked out (for example, I'm pretty sure it would be a more complex type than just `List<string>`) but you get the general idea.

**Comment by jkodroff** [comment]
You could do this:
```
var uncountableWords = new ["ml", "oz", "tbsp", "tsp", "l"];
Inflector.Vocabs.Add(new InflectorVocabulary
{
    Uncountable = uncountableWords
}, "volumes"); 
// "volumes" is an optional name parameter so you could remove it if you wanted to later
// it's "volumes" because these are all units of volume
```

AND this:
```
Inflector.Vocabs.Add(
  InflectorVocabulary.FromFile("volumes-humanizer-vocab.json", VocabFileFormat.Json),
  "volumes"
);
```

Someday you might find yourself adding `en-gb-humanizer-vocab.json` for UK English, and you're not going to want to have to hard code that in your codebase.

The main point from my perspective is that you should be able to add and remove vocabs at runtime, and they can be written in C# or in an external JSON file or whatever IMO.  I would *recommend* an external file rather than C# because you shouldn't need to re-compile and re-deploy to add/remove words, but in your particular case I don't think it matters much since that list is unlikely to change.

I'm kinda taking this tiny problem and smashing it with a sledgehammer I know, but this change would make the library much more expandable in the future if the owners wanted to go in that direction.  I think we can balance @qJake 's simple use case of "I just want a couple of additions to the dictionary" with "I want to add an entire other language to this library".

**Comment by MehdiK** [comment]
> Are you open to something more ambitious
Yes, please. That would be awesome. 

> What would you think of being able to add a humanizer-dict.json file to the output directory and have it automatically picked up
I am personally against any config file. The only reason having a configuration file might makes sense is what @jkodroff said: "*you shouldn't need to re-compile and re-deploy to add/remove words*" which I'm strictly against. I don't want anyone to deploy anything anywhere without it being version controlled and going through the CD pipeline. In my teams/projects, if one wants to change configuration values in any environment, they'll have to make a commit and push it through CI/CD with tests verifying the behavior of app using that config before it's deployed anywhere. For that reason, I don't want file injection as part of the core. Of course if anyone's keen they can write their own Vocabulary implementation that reads from wherever they want.

> you should be able to add and remove vocabs at runtime
Agreed; but that doesn't require json injection. Adding to vocab should be an API call which means you can feed it from anywhere (a web service or a json file).

I am so looking forward to this addition. Thanks for the discussions and the suggestions guys. Awesome stuff!

**Comment by jkodroff** [comment]
@MehdiK That all sounds good.  I'll work on it this week and will keep you appraised of my progress.  If you'd like to assign the case to me and it doesn't require giving me any undeserved access to this repo, please go ahead.

**Comment by MehdiK** [comment]
Thanks @jkodroff. That's awesome. 

We use Pull Requests in Humanizer. Please fork the repo, make the changes and submit a PR. We will then review and merge it. Thanks.

**Comment by qJake** [comment]
Hey, this is awesome! Good job, @dmytro-ielkin!

Could you (or @MehdiK) update the Readme to provide an example of providing your own vocabulary?

**Comment by dmytro-ielkin** [comment]
Hi @qJake, This wasn't me. I just did changes that were already done by @jkodroff in scope of this PR. I was working on a different one.

**Comment by jkodroff** [comment]
@qJake I ended up scaling back the proposed changes a little bit so that I wasn't doing anything that wasn't being asked for.  You can see the docs for the new public methods [here](https://github.com/MehdiK/Humanizer#adding-words).

I also added most (all, I hope) of the terms you wanted excluded as part of my PR, which you can see [here](https://github.com/MehdiK/Humanizer/blob/master/src/Humanizer/Inflections/Vocabularies.cs#L97-L101).

**Comment by qJake** [comment]
Awesome! Thanks @jkodroff! :smile:

**Comment by MehdiK** [comment]
:+1: 

That was an awesome addition @jkodroff. Thanks.

**Comment by ptrimble33** [comment]
@qJake how can I get in touch with you regarding some HUE custom development opportunities?
Thanks,
Phil 
phil.trimble@patienttrak.net
