### ISSUE TITLE
How to handle common abbreviations with a number such as 2D and 3D

### ISSUE THREAD

**Issue by jnm2** [MehdiK/Humanizer#404]
`ChartType.Bar3D.Humanize()` outputs `Bar 3 d`. A desirable output in this kind of situation would pretty universally be `Bar 3D`.

Is there a way to let Humanizer know that '3D' and '2D' are special abbreviations?

**Comment by MehdiK** [comment]
No there isn't; but you could put a `Description` attribute to override the behaviour. FWIW`"Bar_3D".Humanize()` will also return `Bar #D`.

**Comment by jnm2** [comment]
`Description` and `Bar_3D` would work if I owned the enum type, but I don't. I guess I'll have to go with a switch statement then.

**Comment by MehdiK** [comment]
We could potentially create a dictionary in Humanizer for words that shouldn't be humanized; but this feels like a very specific need. If more users get behind this request, we'll implement it.

**Comment by MrKWatkins** [comment]
I have a similar need; I have some words that have special capitalisation (brand names in my case) which I don't want altered. For example I would want "RoboCopIsAGreatFilm".Humanize() to output "RoboCop is a great film" and not "Robo cop is a great film".
