### ISSUE TITLE
int.ToWords() extension method is not using current thread's culture by default.

### ISSUE THREAD

**Issue by TylerKalosza** [MehdiK/Humanizer#409]
Currently using Humanizer version 1.35.0.

When I set my regional settings to **French (France)** I would expect that if I don't supply any parameters than the method will use my system's current regional setting as default.

The tooltip says:
> If null, current thread's UI culture is used.

This is what I believe should work:
```c#
var text = integer.ToWords();
```
This is what I have to do to make it work:
```c#
var cultureInfo = Thread.CurrentThread.CurrentCulture;
var text = integer.ToWords(cultureInfo);
```

I hope this helps improve an already outstanding NuGet package.  :smiley:

**Comment by hazzik** [comment]
Humanizer uses **UI** culture, `Thread.CurrentThread.CurrentUICulture`. And this is exactly what the quoted text says.

**Comment by hazzik** [comment]
Actually, after some investigation I think that we need to change to use `CurrentCulture` instead of `CurrentUICulture`

**Comment by MehdiK** [comment]
@TylerKalosza thanks for reporting the issue.

@hazzik can you please provide link to your findings?

**Comment by hazzik** [comment]
There are a lot of links:

* http://stackoverflow.com/q/329033/259946
* http://www.siao2.com/2007/01/11/1449754.aspx
* http://stackoverflow.com/a/6814736/259946
* http://donkeybridge.blogspot.co.nz/2011/03/dotnet-currentculture-vs.html
* http://www.pchenry.com/Home/tabid/36/EntryId/107/CurrentCulture-vs-CurrentUICulture-whats-the-difference.aspx
* http://blogs.msdn.com/b/ddietric/archive/2008/02/05/yacvcp-yet-another-currentculture-vs-currentuiculture-post.aspx
* http://waf.codeplex.com/discussions/550392
* http://leecampbell.blogspot.co.nz/2008/06/currentculture-vs-currentuiculture.html

But the question itself is really complicated, and I'm not sure that I was right by the time of previous comment.

**Comment by hazzik** [comment]
We need to consider what is the correct current culture for each and every method. In this particular case words should use the UI culture.

**Comment by TylerKalosza** [comment]
This was my first post on GitHub, I'm glad to see it was positively received.  I noticed that I should have maybe included more details such as my output.

Anyway, thanks for taking the time to look at this, and thanks for the quick response guys!

**Comment by MehdiK** [comment]
Thanks @hazzik.

We look forward to seeing more from you @TylerKalosza :)
