### ISSUE TITLE
DateTime.Humanize is not taking Timezone information into account

### ISSUE THREAD

**Issue by dampee** [MehdiK/Humanizer#418]
It seems Humanize() is not taking the correct timezone.    The results are taking UTC dates not the local dates.  My current timezone is CEST (currently UTC + 2).  When I add 2 hours to the current DateTime.Now, it returns 4 hours further.  I am testing version 1.36.

    static void Main(string[] args)
        {
            Console.WriteLine(DateTime.Now.AddHours(30).Humanize());  // tomorrow
            Console.WriteLine(DateTime.Now.AddHours(2).Humanize()); // 4 hours from now
            Console.WriteLine(DateTime.Now.AddMinutes(-2).Humanize()); // an hour from now 
            Console.WriteLine(DateTimeOffset.UtcNow.AddHours(2).Humanize()); // 2 hours from now (correct)
            Console.Read();
        }

**Comment by MehdiK** [comment]
Thanks for reporting this.

Can you please try v1.34 to see if you get the desired behavior? A change
was introduced to this method on v1.35 which wasn't supposed to be a
breaking change but this feels related to that !!

**Comment by dampee** [comment]
Tried 1.33.7 and 1.34, but doesn't seem to solve the issue.

**Comment by MehdiK** [comment]
Oh, actually I take that back. Humanizer by default uses UTC timezone. If
you want your time to be compared against local time then you should pass a
false to the utcDate param. More info on the readme
https://github.com/MehdiK/Humanizer#humanize-datetime

Hope this answers your question

**Comment by dampee** [comment]
Solves the issue.  But if you are "humanizing" you tend to use local dates, and not UTC.  Isn't it better to supply have false as default value for the utcDate ?
Or can we overwrite a default configuration somewhere?

**Comment by dampee** [comment]
On second though, I can't really care at the moment, because this is only true for desktop applications.  I'll be working on a (cloud) server, which is running in UTC anyway.   I'll close the issue. 

(but i still think you should consider passing false as default for the utcDate param)

**Comment by MehdiK** [comment]
Thanks @dampee. I think the default value should be UTC. You should almost never use anything other than UTC or DateTimeOffset values anywhere otherwise things get really ugly over different timezones or over daylight saving. In fact some devs think that [DateTime should be deprecated](https://github.com/dotnet/coreclr/issues/45).
