### ISSUE TITLE
Ignoring certain words?

### ISSUE THREAD

**Issue by mpetito** [MehdiK/Humanizer#427]
Is it possible to ignore or remove certain words in the humanized text?  For instance, if I have a property named *AddressStateId* I'd like the humanized text to be *Address State* instead of *Address State Id*.  Perhaps have the removed words limited to suffixes (or prefixes)?

Thanks!

**Comment by MehdiK** [comment]
No it's not. This is a very specific need and IMO not a good fit for the core framework. I'd create a wrapper like:

```
string Humanize(this string input, params string[] ignoreList)
{
   var humanized = input.Humanize();
   /// now remove the ignored items from the result humanized. 
}
```

I hope this helps.
