### ISSUE TITLE
Use xUnit Runner nuget package

### ISSUE THREAD

**Issue by sluu99** [MehdiK/Humanizer#430]
Hi all!

I'm new to our codebase and was trying to debug through some test cases to get familiar with the code paths. I was having a hard time running those test cases externally (from the `tools` folder). xUnit has an official nuget package that allows running (and debugging) test cases right from VS. More info here: http://xunit.github.io/docs/running-tests-in-vs.html

What's your thought on the matter?

**Comment by MehdiK** [comment]
I'm happy for that to be added. Thanks.

**Comment by sluu99** [comment]
Cool! I'll send a PR sometime late this week.

**Comment by sluu99** [comment]
It appears that this extension counts tests a bit differently. I suspect it's counting unique tests and not the inline data:

![image](https://cloud.githubusercontent.com/assets/1189909/8346758/5c4fde86-1ab6-11e5-9f6e-6f5421f2caca.png)

vs.  

![image](https://cloud.githubusercontent.com/assets/1189909/8346808/e135158a-1ab6-11e5-8710-29c31ccb6793.png)


However, I verified that debugging a test case will run through all the dimensions, in no particular order:

![image](https://cloud.githubusercontent.com/assets/1189909/8346828/3be9c926-1ab7-11e5-8b06-8c8b94e803c3.png)

![image](https://cloud.githubusercontent.com/assets/1189909/8346860/7c4aa8d2-1ab7-11e5-90f5-33bdc4b42841.png)
