### ISSUE TITLE
(DateTime.UtcNow.AddMinutes(-5) - DateTime.UtcNow).Humanize() results in arguments out of range of valid values

### ISSUE THREAD

**Issue by htapal** [MehdiK/Humanizer#436]
Just upgraded Humanizer to latest version from 1.34.0 to 1.36.0 and started receiving errors when Humanizing a timespan with a negative value.

> (DateTime.UtcNow.AddDays(-5) - DateTime.UtcNow).Humanize()
Specified argument was out of the range of valid values.
Parameter name: count

**Comment by htapal** [comment]
I downgraded to 1.36.0 and that version doesn't exhibit this issue.  It correctly handles a negative time span as "no time value" message.

**Comment by MehdiK** [comment]
Thanks for reporting this @htapal. Would you be able to send a PR with a supporting test please?

**Comment by jeremysimmons** [comment]
Suggest merging this with #434

**Comment by MehdiK** [comment]
This is fixed by #438 although it will not report the negative values as 'no time value'. It will Humanize it as if it's a positive value.

**Comment by htapal** [comment]
Thanks @MehdiK.  Apologies for the silence as I'd been traveling.  I'm assuming this will be included in the next release?

**Comment by MehdiK** [comment]
No worries. Yup!

**Comment by MehdiK** [comment]
Now up on NuGet
