### ISSUE TITLE
Would adding tense to DateTime.At make sense

### ISSUE THREAD

**Issue by MisinformedDNA** [MehdiK/Humanizer#444]
I needed to make sure that all my dates were in the future, decided to do the past as well. Would something like this be worth adding to this library?

```csharp
        public static DateTime At(this DateTime date, int hour, int min = 0, int second = 0, int millisecond = 0, Tense tense = Tense.Today)
        {
            var determinedDate = Humanizer.PrepositionsExtensions.At(date, hour, min, second, millisecond);
            
            switch (tense)
            {
                case Tense.Today:
                    return determinedDate;
                case Tense.Future:
                    return determinedDate < date ? determinedDate.AddDays(1) : determinedDate;
                case Tense.Past:
                    return determinedDate > date ? determinedDate.AddDays(-1) : determinedDate;
            }

            throw new ArgumentOutOfRangeException("tense");
        }
    }

    public enum Tense
    {
        Today,
        Future,
        Past
    }
```

**Comment by MehdiK** [comment]
Thanks for the suggestion. I'm not quite sure I understand the usage though? Why do you add or remove a day based on tense? How would you use this method?

**Comment by MisinformedDNA** [comment]
An example would be scheduling a task to send a certain email at 8am, for instance. If it's noon, I don't want to schedule the task in the past, I want it to occur the next time it is 8am.

A more complicated example would be for delaying the visibility of messages ([initialVisibilityDelay](https://msdn.microsoft.com/en-us/library/azure/dn434832.aspx?f=255&MSPPError=-2147217396)) in Azure queues.

So for this I went a step farther. It's a simple method, but it's more readable.

```csharp
        public static TimeSpan Until(this DateTime date, DateTime futureDate)
        {
            return futureDate - date;
        }
```

The final code looks like

```csharp
            var delay = now.Until(now.At(8, 0, tense: Tense.Future));
```

Which basically reads "How much time until the time is 8:00am, in the future?"

Maybe the naming could be better, but that's the general idea. `Until` could maybe be `TimeUntil`? It does return a TimeSpan, so it could make better sense.

**Comment by MehdiK** [comment]
Thanks for explaining this. I see how this could be useful but it seems like a very specific need and feels a bit confusing. On the first look this API is going to be confusing and one would need to read the docs before s/he can make sense of it. So unless we can make the API self-explanatory, I'm not too keen tbh.

Thanks.
