### ISSUE TITLE
Can we compile using VS2012?

### ISSUE THREAD

**Issue by cvbarros** [MehdiK/Humanizer#448]
I am trying to get started with Humanizer to contribute but I only have VS2012 available. Community / Express aren't currently an option. Is it possible to contribute using VS2012?

I'm asking this because project is failing to build, apparently because of #325 .

Edit:  I'm running VS2012 Update 4 with Windows 8.1 Pro.

Thanks!

**Comment by MehdiK** [comment]
IIRC it should be fine with VS2012. The only thing you need to install is the WP8.1 SDK.

Why not use VS2013 Community Edition?! It's free and better :)

**Comment by cvbarros** [comment]
I think WP 8.1 SDK requires VS2013+, or am I missing something? Thanks!

**Comment by MehdiK** [comment]
I think you're right. Been a while since I used VS2012. I'm an OSX user and run my .Net projects in VS2015 in VirtualBox.

Closing this issue now. Happy to discuss this further if needed.
