### ISSUE TITLE
ByteSize trims number with format string

### ISSUE THREAD

**Issue by Suchiman** [MehdiK/Humanizer#450]
If you feed 0 to a bytesize method and give it a format string, it will represent them as bits, but not 0 bit but just empty bit.
```csharp
1.Bytes().ToString("#.##") -> "1 B"
0.Bytes().ToString("#.##") -> " b"
0.Bytes().ToString() -> "0 b"
```

**Comment by MehdiK** [comment]
Thanks for reporting the bug @Suchiman.

**Comment by Raathigesh** [comment]
The `ToString()` method will ignore the digit if it is zero. Providing the string format as `0.Bytes().ToString("0.##")` will return `0 b`. Should we fix this or the appropriate format string should be provided ?

**Comment by MehdiK** [comment]
This is certainly a bug that needs to be fixed. I don't think the 0 should go missing and I don't think it should report it as `b`. If it's Byte it should be reported as `B`. A fix would be nice.

**Comment by Raathigesh** [comment]
`(.5).Kilobytes().ToString()` reports as `512 B`. So Isn't it acceptable to report `0.Bytes().ToString()` as `0 b` ?

**Comment by MehdiK** [comment]
Good point. I agree with reporting `b` @Raathigesh.
