### ISSUE TITLE
Support dotnet TFM

### ISSUE THREAD

**Issue by devhawk** [MehdiK/Humanizer#451]
Humanizer is currently not compatible with .NET Core / ASP.NET 5. Given it's a PCL, I suspect that .NET core support is primarily a matter of updating how the NuGet package is built and not much (if any) in the way of source code changes.

Details on new dotnet TFM are here: http://oren.codes/2015/07/29/targeting-net-core/

**Comment by MehdiK** [comment]
Thanks @devhawk. Yeah, we should do this sooner than later. Thanks for the pointer. Will check it out.

**Comment by onovotny** [comment]
@MehdiK, do you want a PR for this? What this really needs is just to be a Profile 259 PCL and an updated Nuspec.

If you still want to support the .NET 4 Client Profile (does anyone really use this?), and/or .NET 4, then I can create another "head" project and move the real files into a Shared Project. That would create the least amount of duplication.

If that works, I can have that over to you very quickly.

**Comment by MehdiK** [comment]
Thanks @onovotny. A PR would be nice.

For now let's do the simplest thing that works and stay away from .Net 4 Client Profile. I don't even know if any of the users use it.

**Comment by onovotny** [comment]
Can I bump the min .net ver in the PCL to 4.5 (it's currently 4.0). That would be the easiest thing, otherwise I need a second pcl that has 4.5 as a minimum.

**Comment by MehdiK** [comment]
That's a major change and I honestly don't feel comfortable making it as part of V1. I am not a big fan of shared project either. 

Maybe we should just start a V2 pre-release!

**Comment by Phyxion** [comment]
I still use .NET 4 CP.

**Comment by onovotny** [comment]
This is now done in commit be6bc12 in the dev branch. Package is on appveyor CI feed

**Comment by onovotny** [comment]
Guess it'd help I put a link to the CI build feed: https://ci.appveyor.com/project/onovotny/humanizer

**Comment by onovotny** [comment]
There's also a MyGet feed now for pre-release builds: https://www.myget.org/feed/Packages/humanizer
I'll update the docs to mention that too
