### ISSUE TITLE
Transform(To.TitleCase) is not working

### ISSUE THREAD

**Issue by donnyv** [MehdiK/Humanizer#452]
When running this line.
var t = "14 INDEPENDENCE WAY".Transform(To.TitleCase);

It does not change it to title case. It looks like you have to normalize it to lower to get it to work.
var t = "14 INDEPENDENCE WAY".ToLower().Transform(To.TitleCase);

**Comment by kunjaltrivedi** [comment]
Hi donnyv,
This is exactly how it should behave as ALL CAPS is considered as an acronym. Only transforming it using ToLower will change the casing here in this example you have provided.
You can achieve exactly what you want by using ToLowerCase and ToTitleCase together. So in your example I would write 

var t = "14 INDEPENDENCE WAY".Transform( To.LowerCase | To.TitleCase);

Hope that helps

**Comment by MehdiK** [comment]
Hi @donnyv,

Yup, as @kunjaltrivedi mentioned this is the desired behaviour as explained in docs [here](https://github.com/MehdiK/Humanizer#humanize-string).
