### ISSUE TITLE
Remove Satellite Assemblies

### ISSUE THREAD

**Issue by toddca** [MehdiK/Humanizer#454]
We are a US company that due to our business only supports English speaking users and as such we do not have any need for all the satellite assemblies installed with this Nuget package. Is there a en only version of this library or any way to configure it such that these assemblies are not included in each referenced project? Or do we need to manually do this with some scripting via deployment?

**Comment by MehdiK** [comment]
Thanks for the comment @toddca. There is no currently no alternative to getting only the locale you want other than removing it yourself. 

This has already been captured in #59 and there is also a workaround mentioned there.

HTH.
