### ISSUE TITLE
Humanize Count

### ISSUE THREAD

**Issue by timothy-shields** [MehdiK/Humanizer#456]
It seems like there isn't any functionality to humanize a count.  Some examples:

    0 => "0"
    14 => "14"
    71004 => "71k"
    51000492 => "5m" (lower precision)
    51000492 => "5.1m" (higher precision)

It seems very similar to `ByteSize` (maybe `Count`?) except you'd have `Count.Ones`, `Count.Hundreds`, `Count.Thousands`, `Count.Millions`, etc.  `Count.Humanize(precision)` would return the count string at that precision.

Example:

    51000492.ToCount().Humanize(1) => "51000492"
    51000492.ToCount().Humanize(0.999) => "5.1m"

Does this functionality exist in the library?  If not, was it excluded by design?  Or has it just not been thought of or implemented?

A good example of this kind of humanization of a count is on StackOverflow: http://stackoverflow.com/questions?sort=votes  Note how the views ("673k views", "2.4m views", etc.) look.

**Comment by MehdiK** [comment]
Thanks for the suggestion @timothy-shields. This feature does not exist because it was never requested.

It would make for a good addition. Did you want to submit a PR? :)

**Comment by aloisdg** [comment]
Just saw this post. I create exactly the same issue ( #457 ) two days ago. I used the searchbox without success. I should just read the issue list.

Well, I wrote the code to handle this. I will rewrite it and submit a PR.

**Comment by aloisdg** [comment]
Code rewrote. Test added. PR coming soon. (tomorrow? :)

**Comment by onovotny** [comment]
This was implemented in https://github.com/MehdiK/Humanizer/pull/459 and is now in dev
