### ISSUE TITLE
Can we build using VS2013?

### ISSUE THREAD

**Issue by aloisdg** [MehdiK/Humanizer#458]
Hello,

During my work on the metric numeral system (see #456). I ran into a problem during the usage of `build.cmd`. The project build without problem in VS2013 (Community Update 5 with WP8.1 SDK on Windows 10). I guess the problem come from the script.

This problem seems related to #448 and #325.

How can I avoid this problem? Can I keep sending a PR?

Thank you

Full error output:

    Microsoft (R) Build Engine version 4.6.79.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.

      All packages listed in packages.config are already installed.
      Humanizer -> C:\Users\alois\Source\Repos\Humanizer\Src\Humanizer\bin\Release\Humanizer.dll
      Humanizer.Tests -> C:\Users\alois\Source\Repos\Humanizer\Src\Humanizer.Tests\bin\Release\Humanizer.Tests.dll
      xUnit.net MSBuild runner (32-bit .NET 4.0.30319.42000)
      xunit.dll:     Version 1.9.1.1600
      Test assembly: C:\Users\alois\Source\Repos\Humanizer\src\Humanizer.Tests\bin\Release\Humanizer.Tests.dll
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error : Humanizer.Tests.ApiApprover.PublicApiApprovalTest.approve_public_api: System.ArgumentException : Process with an Id of 9876 is not running.
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at System.Diagnostics.Process.GetProcessById(Int32 processId)
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Reporters.VisualStudioReporter.GetProcessAndParent() in c:\code\ApprovalTests.Net\ApprovalTests\Reporters\VisualStudioReporter.cs:line 38
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Reporters.VisualStudioReporter.LaunchedFromVisualStudio() in c:\code\ApprovalTests.Net\ApprovalTests\Reporters\VisualStudioReporter.cs:line 31
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Reporters.VisualStudioReporter.IsWorkingInThisEnvironment(String forFile) in c:\code\ApprovalTests.Net\ApprovalTests\Reporters\VisualStudioReporter.cs:line 26
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Reporters.FirstWorkingReporter.<>c__DisplayClass1.<Report>b__0(IEnvironmentAwareReporter x) in c:\code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs:line 24
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received) in c:\code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs:line 24
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Approvers.FileApprover.ReportFailur(IApprovalFailureReporter reporter) in c:\code\ApprovalTests.Net\ApprovalTests\Approvers\FileApprover.cs:line 55
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Core.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in c:\code\ApprovalTests.Net\ApprovalTests\Core\Approvals.cs:line 12
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 45
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 97
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at ApprovalTests.Approvals.Verify(String text) in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 124
    C:\Users\alois\Source\Repos\Humanizer\build.proj(24,5): error :    at Humanizer.Tests.ApiApprover.PublicApiApprovalTest.approve_public_api() in c:\Users\alois\Source\Repos\Humanizer\src\Humanizer.Tests\ApiApprover\PublicApiApprovalTest.cs:line 16
    Tests: 5995, Failures: 1, Skipped: 0, Time: 1.767 seconds

**Comment by onovotny** [comment]
What version of VS are you using? Can you use VS 2015 Community? That enables use of the new C# 6 feature-set.

**Comment by aloisdg** [comment]
I am using VS 2013. I wont switch for now. I live in India and our connexion is a bit broken.

**Comment by onovotny** [comment]
Will close this out for now. Currently the c# 6 feature use is limited to the `dev` branch, but that'll change once 2.0 is ready for release.
