### ISSUE TITLE
Possible to change a single string value?

### ISSUE THREAD

**Issue by eddiegroves** [MehdiK/Humanizer#460]
I've got a requirement to change two string values we generate using Humaziner:

* `one month ago` to `last month`
* `one month from now` to `next month`

Just wondering if there's a simple way to do this?
Cheers!

**Comment by aloisdg** [comment]
If you are looking for a quick fix in your code, a quick `if/else` will do the job. If you are looking to improve the library, I think you are going to play with [DateTimeHumanizeAlgorithms.cs](https://github.com/MehdiK/Humanizer/blob/master/src/Humanizer/DateTimeHumanizeStrategy/DateTimeHumanizeAlgorithms.cs) and [ResourceKeys.DateHumanize.cs](https://github.com/MehdiK/Humanizer/blob/master/src/Humanizer/Localisation/ResourceKeys.DateHumanize.cs) for the localization. I think it will be a nice idea.

disclaimer : I dont know the project very well. I am a beginner here.

**Comment by MehdiK** [comment]
The text is all read from the resource files. Changing the value in the resource file will change the output.

**Comment by eddiegroves** [comment]
Thanks for the responses guys.

If I understand correctly, the resource files are compiled to DLLs so I would need to clone the project and produce my own version of the resource with the required changes?

For now I've just gone with a more pragmatic approach - albeit one that might not scale too well in the future (I have no i18n requirements, yet...)

```
string label = date.Humanize(dateToCompareAgainst: DateTime.Today);
if (label == "one month ago")
{
    label = "last month";
}
else if (label == "one month from now")
{
    label = "next month";
}
```

I'll close this issue in a few days if nobody else has any other tips :)
