### ISSUE TITLE
Build warning VS2015

### ISSUE THREAD

**Issue by cristianst85** [MehdiK/Humanizer#470]
I'm getting a warning when I try to build Humanizer.

This is from VS2015:

Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	Humanizer.MvcSample			

And from console:

D:\Repositories\Humanizer>build.cmd
  MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
  All packages listed in packages.config are already installed.
  Humanizer -> D:\Repositories\Humanizer\Src\Humanizer\bin\Release\Humanizer.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\Repositories\Humanizer\samples\Humanizer.MvcSample\Humanizer.MvcSample.csproj]
  Humanizer.MvcSample -> D:\Repositories\Humanizer\samples\Humanizer.MvcSample\bin\Humanizer.MvcSample.dll
  Humanizer.Tests -> D:\Repositories\Humanizer\Src\Humanizer.Tests\bin\Release\Humanizer.Tests.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
  xUnit.net MSBuild Runner (32-bit .NET 4.0.30319.42000)
    Discovering: Humanizer.Tests (app domain = on [shadow copy], method display = Method)
    Discovered:  Humanizer.Tests (running 1164 test cases)
    Starting:    Humanizer.Tests (parallel test collections = on, max threads = 4)
11/1/2015 2:41:11 PM ~000001ms Variable: approvalFrame = ''
11/1/2015 2:41:11 PM ~000136ms Variable: approvalFrame = ''
11/1/2015 2:41:11 PM ~000001ms Variable: approvalFrame = ''
11/1/2015 2:41:11 PM ~000001ms Variable: approvalFrame = 'Humanizer.Tests.PublicApiApprovalTest.approve_public_api()'
11/1/2015 2:41:11 PM ~000031ms Variable: frame = 'Humanizer.Tests.PublicApiApprovalTest.approve_public_api()'
    Finished:    Humanizer.Tests
  === TEST EXECUTION SUMMARY ===
     Humanizer.Tests  Total: 6422, Errors: 0, Failed: 0, Skipped: 0, Time: 5,187s

D:\Repositories\Humanizer>

---
Microsoft Visual Studio Community 2015. (version 14.0.24627.00 Update 1 RC)
OS: Windows 7 x64.

**Comment by onovotny** [comment]
Hi @cristianst85, thanks for the report. This started to happen once the MVC project was switched to .NET 4.6 from what it was before. The NuGet packages need to get re-installed to fix this up as some of the packages have different references in 4.6. I'd be happy to take a PR if you're able to do that.

The easiest way to do that is with the package manager console and the `reinstall` switch: https://docs.nuget.org/consume/reinstalling-packages

**Comment by cristianst85** [comment]
Thank you for the fast response, @onovotny. I'll give it a try.
